### ISSUE TITLE
Api tìm kiếm, lọc và sắp xếp contracts

### ISSUE THREAD

**Issue by maqmatic** [qvan7um/video-game-rental-service#46]
https://github.com/qvan7um/video-game-rental-service/wiki/API_Contracts

**Comment by tson420** [comment]
Tìm kiếm contracts theo trường nào ông?

**Comment by maqmatic** [comment]
Xin lỗi t quên ko để ý mail. Chắc là tìm kiếm theo tất cả các trường trừ cái Id thôi.
