### ISSUE TITLE
Hiển thị media (gồm trailer, screenshot) của game trong trang thông tin chi tiết của game

### ISSUE THREAD

**Issue by maqmatic** [qvan7um/video-game-rental-service#85]
https://github.com/qvan7um/video-game-rental-service/wiki/Trang-th%C3%B4ng-tin-game

**Comment by ThanhNhan411** [comment]
[Trang thông tin chi tiết game](https://github.com/qvan7um/video-game-rental-service/wiki/Trang-qu%E1%BA%A3n-l%C3%BD-game_Chi-ti%E1%BA%BFt-game)
